apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: predicat
spec:
  project: default
  source:
    repoURL: https://github.com/InseeFrLab/demo-apps.git
    targetRevision: HEAD
    path: apps/predicat
  destination:
    server: https://kubernetes.default.svc
    namespace: projet-predicat
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
