keycloak:
  image:
    tag: 11.0.3
    
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    rules:
      - host: keycloak-demo-fc.dev.insee.io
        paths:
          - /
    tls:
      - hosts:
          - keycloak-demo-fc.dev.insee.io

  startupScripts:
    # We need to add keycloak vault configuration because of
    # https://github.com/codecentric/helm-charts/issues/241
    secret-vault.cli: |
        embed-server --server-config=standalone-ha.xml --std-out=echo
        batch
        echo configuring vault

        /subsystem=keycloak-server/spi=vault/:add
        /subsystem=keycloak-server/spi=vault/provider=files-plaintext/:add(enabled=true,properties={dir => "/opt/jboss/keycloak/secrets/"})
        /subsystem=keycloak-server/spi=vault:write-attribute(name=default-provider,value=files-plaintext)
        echo Finished configuring vault

        run-batch
        stop-embedded-server

  extraInitContainers: |
    - name: realm-ext-provider
      image: curlimages/curl
      imagePullPolicy: IfNotPresent
      command:
        - sh
      args:
        - -c
        - |
          curl -L -o /extensions/keycloak-franceconnect.jar https://github.com/InseeFr/Keycloak-FranceConnect/releases/download/2.2/keycloak-franceconnect-2.2.jar
      volumeMounts:
        - name: extensions
          mountPath: /extensions

  extraVolumeMounts: |
    - name: extensions
      mountPath: /opt/jboss/keycloak/standalone/deployments
    - name: clientsecret
      mountPath: "/opt/jboss/keycloak/secrets/"
      readOnly: true
    - name: test-fc-realm
      mountPath: "/realm"
  
  extraVolumes: |
    - name: extensions
      emptyDir: {}
    - name: clientsecret
      secret:
        secretName: clientsecret
    - name: test-fc-realm
      configMap:
        name: {{ .Release.Name }}-test-fc-realm

  postgresql:
    enabled: false

  extraEnv: |
    - name: KEYCLOAK_IMPORT
      value: /realm/test-fc.json
    - name: KEYCLOAK_LOGLEVEL
      value: INFO
    - name: PROXY_ADDRESS_FORWARDING
      value: "true"
    - name: JAVA_OPTS
      value: >-
        -XX:+UseContainerSupport
        -XX:MaxRAMPercentage=50.0
        -Djava.net.preferIPv4Stack=true
        -Djboss.modules.system.pkgs=$JBOSS_MODULES_SYSTEM_PKGS
        -Djava.awt.headless=true
        -Dkeycloak.profile=preview
        -Dkeycloak.profile.feature.upload_scripts=enabled

  
 
