addok:
  ingress:
    # No ingress as we are using Gravitee as API manager
    enabled: false
  init:
    enabled: true
    image: curlimages/curl
    command: ["curl"]
    args:
      [
        "-o",
        "/data/addok.db",
        "-L",
        "https://minio.lab.sspcloud.fr/projet-addok/addok-cog.db",
      ]
  redis:
    init:
      enabled: true
      image: curlimages/curl
      command: ["curl"]
      args:
        [
          "-o",
          "/data/dump.rdb",
          "-L",
          "https://minio.lab.sspcloud.fr/projet-addok/dump-cog.rdb",
        ]