predicat:
  ingress:
    enabled: false
  init:
    args:
    - mc alias set minio $S3_URL $S3_USER $S3_PASSWORD --api S3v4; mc cp --recursive minio/projet-predicat/modeles/
      /data/
    command:
    - /bin/sh
    - -c
    enabled: true
    env:
      S3_PASSWORD: changeme
      S3_URL: https://minio.lab.sspcloud.fr/
      S3_USER: predicat
    image: minio/mc
